"""add audit log hash chain

Revision ID: 7f54c1eb5e89
Revises: 3ee228696375
Create Date: 2026-04-04 17:37:27.953779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f54c1eb5e89'
down_revision: Union[str, Sequence[str], None] = '3ee228696375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('entry_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_log', sa.Column('previous_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_audit_log_entry_hash'), 'audit_log', ['entry_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entry_hash'), table_name='audit_log')
    op.drop_column('audit_log', 'previous_hash')
    op.drop_column('audit_log', 'entry_hash')
    # ### end Alembic commands ###
