"""Initial schema snapshot — legacy proxy tables.

Revision ID: 0001_initial_snapshot
Revises:
Create Date: 2026-04-13

Snapshots the three tables that the proxy created via raw CREATE TABLE IF NOT
EXISTS in mcp_proxy/db.py::_SCHEMA_SQL prior to ADR-001 Phase 1. DDL is
intentionally hand-written (not autogenerated) so that existing SQLite
deployments can be `alembic stamp`-ed at this revision without schema drift.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_snapshot"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "internal_agents",
        sa.Column("agent_id", sa.Text(), primary_key=True, nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("capabilities", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("api_key_hash", sa.Text(), nullable=False),
        sa.Column("cert_pem", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False, server_default="1"),
    )

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("timestamp", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
    )
    op.create_index("idx_audit_log_agent_id", "audit_log", ["agent_id"])
    op.create_index("idx_audit_log_timestamp", "audit_log", ["timestamp"])
    op.create_index("idx_audit_log_request_id", "audit_log", ["request_id"])

    op.create_table(
        "proxy_config",
        sa.Column("key", sa.Text(), primary_key=True, nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("proxy_config")
    op.drop_index("idx_audit_log_request_id", table_name="audit_log")
    op.drop_index("idx_audit_log_timestamp", table_name="audit_log")
    op.drop_index("idx_audit_log_agent_id", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("internal_agents")
